---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install java
  yum:
    name: "java-{{ java_version }}-openjdk-devel"
    state: 'present'
- name: Install maven
  unarchive:
    src: http://mirrors.ircam.fr/pub/apache/maven/maven-3/{{ mvn_version }}/binaries/apache-maven-{{ mvn_version }}-bin.tar.gz
    dest: /opt/
    remote_src: yes

- name: Symbolic link
  file:
      src: /opt/apache-maven-{{ mvn_version }}
      dest: /opt/apache-maven
      state: link

- name: Update /etc/environment with mvn in PATH & JAVA_HOME ec2
  shell: echo -e "PATH=/opt/apache-maven/bin:$PATH \nJAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk/" > /etc/environment
  when: ec2 == true

- name: Update /etc/environment with mvn in PATH & JAVA_HOME gcp
  shell: echo -e "PATH=/opt/apache-maven/bin:$PATH \nJAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk/" > /etc/environment
  when: gcp == true
