---
- name: restart tigervnc
  systemd:
    state: restarted
    daemon_reload: yes
    name: vncserver@:1

- name: restart tomcat
  systemd:
    state: restarted
    daemon_reload: yes
    name: tomcat

- name: restart guacd
  systemd:
    state: restarted
    daemon_reload: yes
    name: guacd
