- name: Get prometheus
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.15.1/prometheus-2.15.1.linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
    owner: prometheus
    group: prometheus

- name: Symbolic link
  file:
      src: /opt/prometheus-2.15.1.linux-amd64
      dest: /opt/prometheus
      state: link

- name: Creates /var/prometheus
  file:
    path: /var/prometheus/
    state: directory
    owner: prometheus
    group: prometheus


- name: Creates /var/log/prometheus
  file:
    path: /var/log/prometheus/
    state: directory
    owner: prometheus
    group: prometheus

- name: Creates /etc/prometheus
  file:
    path: /etc/prometheus/
    state: directory
    owner: prometheus
    group: prometheus

- name: Create /etc/prometheus/prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: '0644'


- name: Ensure prometheus unit file is available.
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644

- name: restart & enable prometheus
  systemd:
    state: started
    name: prometheus
    enabled: true

- name: Get source of prometheus jmx exporter
  unarchive:
    src: https://github.com/prometheus/jmx_exporter/archive/parent-0.12.0.tar.gz
    dest: /opt/
    remote_src: yes

- name: Symbolic link
  file:
      src: /opt/jmx_exporter-parent-0.12.0
      dest: /opt/prometheus-jmx-exporter
      state: link

- name: maven build
  shell: mvn package -DskipTests
  args:
    chdir: /opt/prometheus-jmx-exporter

- name: copy artifact to /opt/jmx_exporter-parent/
  shell: cp /opt/prometheus-jmx-exporter/jmx_prometheus_javaagent/target/jmx_prometheus_javaagent-0.12.0.jar /opt/prometheus-jmx-exporter/jmx_prometheus_javaagent.jar
