
- name: Creates /etc/zookeeper
  file:
    path: /etc/zookeeper/
    state: directory
    owner: kafka
    group: kafka

- name: Creates /var/zookeeper
  file:
    path: /var/zookeeper/
    state: directory
    owner: kafka
    group: kafka

- name: Creates /var/log/zookeeper
  file:
    path: /var/log/zookeeper/
    state: directory
    owner: kafka
    group: kafka



- name: Create /etc/zookeeper/zookeeper.properties
  template:
    src: zookeeper.properties.j2
    dest: /etc/zookeeper/zookeeper.properties
    owner: kafka
    group: kafka
    mode: '0644'

- name: Ensure Zookeeper unit file is available.
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart zookeeper

- name: restart & enable zookeeper
  systemd:
    state: started
    name: zookeeper
    enabled: true
