---
- name: restart zookeeper
  systemd:
    state: restarted
    daemon_reload: yes
    name: zookeeper

- name: restart kafka-1
  systemd:
    state: restarted
    daemon_reload: yes
    name: kafka-2

- name: restart kafka-2
  systemd:
    state: restarted
    daemon_reload: yes
    name: kafka-2

- name: restart kafka-3
  systemd:
    state: restarted
    daemon_reload: yes
    name: kafka-2
