---
- name: install useful packages
  yum:
    name:
      - chromium
      - nautilus
      - gedit

- name: Create ~/change_vnc_screen_resolution.sh
  template:
    src: change_vnc_screen_resolution.sh.j2
    dest: /home/student/change_vnc_screen_resolution.sh
    owner: student
    group: student
    mode: '0744'

- name: Creates /home/student/Desktop
  file:
    path: /home/student/Desktop
    state: directory
    owner: student
    group: student


- name: Create ~/Desktop/README-change_resolution.txt
  template:
    src: README-change_resolution.txt.j2
    dest: /home/student/Desktop/README-change_resolution.txt
    owner: student
    group: student
    mode: '0644'

- name: Download IntelliJ
  unarchive:
    src: https://download.jetbrains.com/idea/ideaIC-2019.3.1.tar.gz?_ga=2.91359706.1161434762.1578240422-1246064796.1575984994
    dest: /home/student
    remote_src: yes
    owner: student
    group: student
