---
- name: install guacamole
  hosts: isep-kafka
  become: yes
  vars_prompt:
    - name: guacamole_client_password
      prompt: "What is guacamole user password ?"
      private: yes
    - name: tigervnc_vncpass
      prompt: "What is the vnc password ?"
      private: yes
  vars:
    - ec2: false
    - gcp: true
  roles:
  - common
  - guacamole
  - kafka
  - misc
